### ISSUE TITLE
Angular 4 Compatibility

### ISSUE THREAD

**Issue by NaLLiFFuNT** [dominique-mueller/angular-notifier#10]
I've updated angular up to 4.0 and notifier is broken. 

I see following 

> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at notifier-notification.component.js:93
    at new ZoneAwarePromise (zone.js:776)
    at NotifierNotificationComponent.show (notifier-notification.component.js:81)
    at NotifierContainerComponent.continueHandleShowAction (notifier-container.component.js:127)
    at NotifierContainerComponent.onNotificationReady (notifier-container.component.js:71)
    at Object.eval [as handleEvent] (NotifierContainerComponent.html:1)
    at handleEvent (core.es5.js:11805)
    at callWithDebugContext (core.es5.js:13013)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12601)
    at dispatchEvent (core.es5.js:8780)
    at core.es5.js:10644
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3840)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:234)
    at SafeSubscriber.next (Subscriber.js:183)
    at Subscriber._next (Subscriber.js:125)
    at notifier-notification.component.js:93
    at new ZoneAwarePromise (zone.js:776)
    at NotifierNotificationComponent.show (notifier-notification.component.js:81)
    at NotifierContainerComponent.continueHandleShowAction (notifier-container.component.js:127)
    at NotifierContainerComponent.onNotificationReady (notifier-container.component.js:71)
    at Object.eval [as handleEvent] (NotifierContainerComponent.html:1)
    at handleEvent (core.es5.js:11805)
    at callWithDebugContext (core.es5.js:13013)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12601)
    at dispatchEvent (core.es5.js:8780)
    at core.es5.js:10644
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3840)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:234)
    at SafeSubscriber.next (Subscriber.js:183)
    at Subscriber._next (Subscriber.js:125)
    at resolvePromise (zone.js:712) [angular]
    at resolvePromise (zone.js:683) [angular]
    at :3002/polyfills.bundle.js:11387:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at ZoneDelegate.webpackJsonp.1856.ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.webpackJsonp.1856.Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (zone.js:464) [<root>]

**Comment by dominique-mueller** [comment]
Can you check that it's not the same problem described in issue #6?

**Comment by NaLLiFFuNT** [comment]
Thanks for your answer, i'll double check it today.

**Comment by dominique-mueller** [comment]
You're probably just missing the Web Animations API polyfill ;)

**Comment by NaLLiFFuNT** [comment]
It was realy so, we removed web-animation polyfill while we were upgrading angular 2 upto angular 4. 
I've added `web-animations-js` package as polyfill.
Critical error has gone, however there're still two errors.

Should i add any other polyfills? Or may be, i did something wrong...

> core.es5.js:1085 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at http://localhost:3002/vendor.bundle.js:121733:95
    at new ZoneAwarePromise (http://localhost:3002/polyfills.bundle.js:11426:29)
    at NotifierNotificationComponent.show (http://localhost:3002/vendor.bundle.js:121721:16)
    at NotifierContainerComponent.continueHandleShowAction (http://localhost:3002/vendor.bundle.js:121325:36)
    at NotifierContainerComponent.onNotificationReady (http://localhost:3002/vendor.bundle.js:121269:14)
    at Object.eval [as handleEvent] (ng:///NotifierModule/NotifierContainerComponent.ngfactory.js:68:24)
    at handleEvent (http://localhost:3002/vendor.bundle.js:12064:119)
    at callWithDebugContext (http://localhost:3002/vendor.bundle.js:13272:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:3002/vendor.bundle.js:12860:12)
    at dispatchEvent (http://localhost:3002/vendor.bundle.js:9042:21)
    at http://localhost:3002/vendor.bundle.js:10904:38
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3002/vendor.bundle.js:4072:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3002/vendor.bundle.js:19447:16)
    at SafeSubscriber.next (http://localhost:3002/vendor.bundle.js:19396:22)
    at Subscriber._next (http://localhost:3002/vendor.bundle.js:19338:26)
    at http://localhost:3002/vendor.bundle.js:121733:95
    at new ZoneAwarePromise (http://localhost:3002/polyfills.bundle.js:11426:29)
    at NotifierNotificationComponent.show (http://localhost:3002/vendor.bundle.js:121721:16)
    at NotifierContainerComponent.continueHandleShowAction (http://localhost:3002/vendor.bundle.js:121325:36)
    at NotifierContainerComponent.onNotificationReady (http://localhost:3002/vendor.bundle.js:121269:14)
    at Object.eval [as handleEvent] (ng:///NotifierModule/NotifierContainerComponent.ngfactory.js:68:24)
    at handleEvent (http://localhost:3002/vendor.bundle.js:12064:119)
    at callWithDebugContext (http://localhost:3002/vendor.bundle.js:13272:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:3002/vendor.bundle.js:12860:12)
    at dispatchEvent (http://localhost:3002/vendor.bundle.js:9042:21)
    at http://localhost:3002/vendor.bundle.js:10904:38
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3002/vendor.bundle.js:4072:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3002/vendor.bundle.js:19447:16)
    at SafeSubscriber.next (http://localhost:3002/vendor.bundle.js:19396:22)
    at Subscriber._next (http://localhost:3002/vendor.bundle.js:19338:26)
    at new Error (native)
    at resolvePromise (http://localhost:3002/polyfills.bundle.js:11362:31) [angular]
    at resolvePromise (http://localhost:3002/polyfills.bundle.js:11333:17) [angular]
    at http://localhost:3002/polyfills.bundle.js:11410:17 [angular]
    at Object.onInvokeTask (http://localhost:3002/vendor.bundle.js:4348:37) [angular]
    at ZoneDelegate.webpackJsonp.1857.ZoneDelegate.invokeTask (http://localhost:3002/polyfills.bundle.js:11047:36) [angular]
    at Zone.webpackJsonp.1857.Zone.runTask (http://localhost:3002/polyfills.bundle.js:10815:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:3002/polyfills.bundle.js:11243:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3002/polyfills.bundle.js:11114:25) [<root>]
defaultErrorLogger	@	core.es5.js:1085
ErrorHandler.handleError	@	core.es5.js:1145
next	@	core.es5.js:4774
schedulerFn	@	core.es5.js:3848
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:234
SafeSubscriber.next	@	Subscriber.js:183
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3834
NgZone.triggerError	@	core.es5.js:4205
onHandleError	@	core.es5.js:4166
webpackJsonp.1857.ZoneDelegate.handleError	@	zone.js:369
webpackJsonp.1857.Zone.runGuarded	@	zone.js:141
_loop_1	@	zone.js:604
drainMicroTaskQueue	@	zone.js:613
ZoneTask.invoke	@	zone.js:464

The second one:
> core.es5.js:1085 ERROR TypeError: this.finishPromiseResolver is not a function
    at NotifierTimerService.finish (http://localhost:3002/vendor.bundle.js:122150:14)
    at http://localhost:3002/vendor.bundle.js:122136:19
    at ZoneDelegate.webpackJsonp.1857.ZoneDelegate.invokeTask (http://localhost:3002/polyfills.bundle.js:11048:31)
    at Object.onInvokeTask (http://localhost:3002/vendor.bundle.js:4348:37)
    at ZoneDelegate.webpackJsonp.1857.ZoneDelegate.invokeTask (http://localhost:3002/polyfills.bundle.js:11047:36)
    at Zone.webpackJsonp.1857.Zone.runTask (http://localhost:3002/polyfills.bundle.js:10815:47)
    at ZoneTask.invoke (http://localhost:3002/polyfills.bundle.js:11110:38)
    at timer (http://localhost:3002/polyfills.bundle.js:12190:29)
defaultErrorLogger	@	core.es5.js:1085
ErrorHandler.handleError	@	core.es5.js:1145
next	@	core.es5.js:4774
schedulerFn	@	core.es5.js:3848
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:234
SafeSubscriber.next	@	Subscriber.js:183
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3834
NgZone.triggerError	@	core.es5.js:4205
onHandleError	@	core.es5.js:4166
webpackJsonp.1857.ZoneDelegate.handleError	@	zone.js:369
webpackJsonp.1857.Zone.runTask	@	zone.js:168
ZoneTask.invoke	@	zone.js:460
timer

**Comment by NaLLiFFuNT** [comment]
I've finally figured out what had been wrong. I imported just `web-animations.min.js` instead of importing `web-animations-next.min.js`.

**Comment by dominique-mueller** [comment]
Just published v2 which is also happy with the default `web-animations-js` polyfill.
