### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by harryhahn2** [dominique-mueller/angular-notifier#6]
I want to use this awesome tool, but I have some trouble with it

when i call this.notifier.notify(...) an TypeError occurs.

i can't find what do i wrong. 

`EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at http://localhost:4200/vendor.bundle.js:110619:95
    at new ZoneAwarePromise (http://localhost:4200/vendor.bundle.js:155500:29)
    at NotifierNotificationComponent.show (http://localhost:4200/vendor.bundle.js:110607:16)
    at NotifierContainerComponent.continueHandleShowAction (http://localhost:4200/vendor.bundle.js:110212:36)
    at NotifierContainerComponent.onNotificationReady (http://localhost:4200/vendor.bundle.js:110156:14)
    at View_NotifierContainerComponent1.handleEvent_1 (/NotifierModule/NotifierContainerComponent/component.ngfactory.js:76:45)
    at View_NotifierContainerComponent1.<anonymous> (http://localhost:4200/vendor.bundle.js:100425:37)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:4200/vendor.bundle.js:50200:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:710:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:659:22)
    at Subscriber._next (http://localhost:4200/vendor.bundle.js:612:26)
    at Subscriber.next (http://localhost:4200/vendor.bundle.js:576:18)
    at EventEmitter.Subject.next (http://localhost:4200/vendor.bundle.js:4313:25)
    at EventEmitter.emit (http://localhost:4200/vendor.bundle.js:50174:76)
    at NotifierNotificationComponent.ngAfterViewInit (http://localhost:4200/vendor.bundle.js:110566:20)`

`error_handler.js:60 Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at notifier-notification.component.js:93
    at new ZoneAwarePromise (zone.js:551)
    at NotifierNotificationComponent.show (notifier-notification.component.js:81)
    at NotifierContainerComponent.continueHandleShowAction (notifier-container.component.js:127)
    at NotifierContainerComponent.onNotificationReady (notifier-container.component.js:71)
    at View_NotifierContainerComponent1.handleEvent_1 (component.ngfactory.js:76)
    at View_NotifierContainerComponent1.<anonymous> (view.js:664)
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:79)
    at NotifierNotificationComponent.ngAfterViewInit (notifier-notification.component.js:40)
    at resolvePromise (zone.js:501) [angular]
    at resolvePromise (zone.js:486) [angular]
    at :4200/vendor.bundle.js:155484:17 [angular]
    at Object.onInvokeTask (ng_zone.js:262) [angular]
    at ZoneDelegate.invokeTask (zone.js:274) [angular]
    at Zone.runTask (zone.js:151) [<root> => angular]
    at drainMicroTaskQueue (zone.js:433) [<root>]
    at HTMLButtonElement.ZoneTask.invoke (zone.js:349) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:359
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:331
onHandleError @ ng_zone.js:292
ZoneDelegate.handleError @ zone.js:246
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:444
drainMicroTaskQueue @ zone.js:453
ZoneTask.invoke @ zone.js:349
zone.js:420 Unhandled Promise rejection: Cannot read property 'then' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'then' of undefined
    at notifier-notification.component.js:93
    at new ZoneAwarePromise (zone.js:551)
    at NotifierNotificationComponent.show (notifier-notification.component.js:81)
    at NotifierContainerComponent.continueHandleShowAction (notifier-container.component.js:127)
    at NotifierContainerComponent.onNotificationReady (notifier-container.component.js:71)
    at View_NotifierContainerComponent1.handleEvent_1 (component.ngfactory.js:76)
    at View_NotifierContainerComponent1.<anonymous> (view.js:664)
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:79)
    at NotifierNotificationComponent.ngAfterViewInit (notifier-notification.component.js:40) TypeError: Cannot read property 'then' of undefined
    at http://localhost:4200/vendor.bundle.js:110619:95
    at new ZoneAwarePromise (http://localhost:4200/vendor.bundle.js:155500:29)
    at NotifierNotificationComponent.show (http://localhost:4200/vendor.bundle.js:110607:16)
    at NotifierContainerComponent.continueHandleShowAction (http://localhost:4200/vendor.bundle.js:110212:36)
    at NotifierContainerComponent.onNotificationReady (http://localhost:4200/vendor.bundle.js:110156:14)
    at View_NotifierContainerComponent1.handleEvent_1 (/NotifierModule/NotifierContainerComponent/component.ngfactory.js:76:45)
    at View_NotifierContainerComponent1.<anonymous> (http://localhost:4200/vendor.bundle.js:100425:37)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:4200/vendor.bundle.js:50200:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:710:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:659:22)
    at Subscriber._next (http://localhost:4200/vendor.bundle.js:612:26)
    at Subscriber.next (http://localhost:4200/vendor.bundle.js:576:18)
    at EventEmitter.Subject.next (http://localhost:4200/vendor.bundle.js:4313:25)
    at EventEmitter.emit (http://localhost:4200/vendor.bundle.js:50174:76)
    at NotifierNotificationComponent.ngAfterViewInit (http://localhost:4200/vendor.bundle.js:110566:20)
consoleError @ zone.js:420
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
ZoneTask.invoke @ zone.js:349
`

**Comment by dominique-mueller** [comment]
Hey, thanks for opening this issue!

Chances are high that it's the Web Animations API creating trouble here. While Chrome already supports lots of its features, some are still missing - such as Promises, resolved once the animation has finished.

Therefore, you probably have to include the Web Animations API polyfill in your application.
- See the docs: https://github.com/dominique-mueller/angular-notifier#polyfills
- Current polyfill implementation: https://github.com/web-animations/web-animations-js (include the web-animations-next.min.js file)

Let me know if that fixes your problem :)

**Comment by harryhahn** [comment]
Great
it works :-).

Thanks.

**Comment by dominique-mueller** [comment]
Perfect! I probably will improve the docs further to reflect the need for this polyfill more clearly. Have fun coding!

**Comment by dominique-mueller** [comment]
Just published v2 which is also happy with the default `web-animations-js` polyfill.
